version: '3'
services:
  proxy:
    build:
      context: ./src      
      dockerfile: Dockerfile
    container_name: myproxy_container
    ports:
      - "12345:12345"
    restart: always
    volumes:
      - ./logs:/var/log/erss
