version: '3'
services:
  proxy:
    build: .
    container_name: myproxy_container
    ports:
      - "12345:12345"
    volumes:
      - ./logs:/var/log/erss
      - ./src:/app/src
      - ./testcases:/app/testcases
